import Head from "next/head";
import { useEffect, useState } from "react";
// import dynamic from "next/dynamic";
import DraggeableForm from "../components/DraggableFormGPT";

// const dyDraggeableForm = dynamic(() => import("../components/DraggeableForm"), {
//  loading: () => 'Loading...',
// });

export default function Home() {
  const [isBrowser, setIsBrowser] = useState(false);

  useEffect(() => {
    // setIsBrowser(process.browser)
    setIsBrowser(typeof window !== "undefined");
  }, []);
  return (
    <>
      <Head>
        <title>Roulette</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isBrowser ? <DraggeableForm /> : null}
    </>
  );
}
